### ISSUE TITLE
csv format change, converter fails

### ISSUE THREAD

**Issue by aclimdler** [ClaireDuSoleil/ClaireDuSoleil.github.io#6]
these are the 2022 headers in turbotax doc from coinbase

```
Transaction Type,Transaction ID,Tax lot ID,Asset name,Amount,Date Acquired,Cost basis (USD),Date of Disposition,Proceeds (USD),Gains (Losses) (USD),Holding period (Days),Data source
```

**Comment by ClaireDuSoleil** [comment]
Thank you for letting me know.  I've updated the code.  Please let me know if there are any issues.

**Comment by aclimdler** [comment]
Thanks. 

Error persists. 

Here's a sample file to test with - [Fake.csv](https://github.com/ClaireDuSoleil/ClaireDuSoleil.github.io/files/10516647/Fake.csv)

**Comment by ClaireDuSoleil** [comment]
Thank you for the sample.  The CSV that you provided appears to be generated in the Coinbase "Taxes" section.  Coinbase generates different CSV files depending on where you are generating them.  The CSV that my webpage is expecting is generated in the "Reports" section, not the "Taxes" section.  If you click on your profile pic or icon and then select Reports-->Transaction history-->Generate Report button then you should get a CSV that contains headers compatible with my code.

Coinbase did just change the column headers slightly for the Reports CSV files so it was broken but the fix I just submitted works now for me.

Also, I see that Coinbase in the Taxes section of their website now generates Turbo Tax files and more complete gain/loss reports which would make my webpage obselete.  Coinbase does require you to add details to each send/receive so they know how to classify it.  My webpage just makes assumptions on send/receive transactions instead.

I hope this helps explain what is happening.  Thank you.

**Comment by aclimdler** [comment]
Oh, thanks for the prompt response and direction. 

I used the turbo tax export, but it's a CSV file for web import, not for turbotax desktop, and it doesn't recognize files on desktop.

**Comment by aclimdler** [comment]
I was able to go to export but got a new error. Is this because I sent ETH?

<img width="447" alt="Screenshot 2023-01-27 at 11 00 48 AM" src="https://user-images.githubusercontent.com/46388583/215172372-9994ff9b-f331-4031-b596-8b2dc2b8c861.png">

**Comment by ClaireDuSoleil** [comment]
Sounds like some transactions where you acquired ETH were not in the original CSV file.  When you generate your report be sure to select All Time.  If you want to filter out transactions so that you only have 2022 transactions, you can do that after the table is generated.
![image](https://user-images.githubusercontent.com/1243158/215181170-e471ff53-b963-4a54-94d9-d4fad54d04d8.png)

**Comment by aclimdler** [comment]
oh, cool thanks for all the work, and appreciate the support. 

Still complains about some smaller ones that I don't know how I got. I'd like to ignore those.
Maybe a warning instead of an error?

**Comment by ClaireDuSoleil** [comment]
Can you show me what you mean by "smaller ones"?  How small?

I don't want to change the code to ignore asset sales where, according to the transaction history, you don't have enough of that asset to fulfill the sale because it could lead to people generating bad tax data and I don't want to be responsible for that.

**Comment by aclimdler** [comment]
> Can you show me what you mean by "smaller ones"? How small?

Sorry. Under $5-$10. 

> I don't want to change the code to ignore asset sales where, according to the transaction history, you don't have enough of that asset to fulfill the sale because it could lead to people generating bad tax data and I don't want to be responsible for that.

Makes sense. Thank you. 

Looking at the data, the transaction type was "reward", and it imported without issue!
Thank you for your work.
